### ISSUE TITLE
consider breaking up this repo in sub repository

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-java#102]
considering the issues we've had with the CI complexity #35 and the fact that SonarCloud doesn't support monorepos #101, we should consider breaking this repo appart in sub repos like the other languages.

**Comment by andreaTP** [comment]
An alternative to breaking down into multiple repos would be to use a multi-project build:
https://docs.gradle.org/current/userguide/multi_project_builds.html#multi_project_builds
