### ISSUE TITLE
Request headers shouldn't be `@Nullable`

### ISSUE THREAD

**Issue by piotrooo** [microsoft/kiota-java#1145]
First of all, thanks for your huge work on this project :heart: 

I have a question about `@Nullable` in the `headers` field in the `BaseRequestConfiguration` class.

In what situations could this field be nullable? This requires API consumers to implement null checks, as it raises the following warnings:

![Screenshot from 2024-03-31 17-58-20](https://github.com/microsoft/kiota-java/assets/2005054/285b35bb-1e21-43bb-a22a-2efc2c22cacf)

This should be an empty object, which cannot be `null`.

**Comment by andrueastman** [comment]
Thanks for raising this @piotrooo 

I believe you are correct given the default initializer present as well at https://github.com/microsoft/kiota-java/blob/46cd68f9fd0d97a1bea96ee86c04862bb5252807/components/abstractions/src/main/java/com/microsoft/kiota/BaseRequestConfiguration.java#L17C6-L17C15

Any chance you'd be willing to submit a PR on this repo to fix this?

**Comment by piotrooo** [comment]
@andrueastman sure.
