### ISSUE TITLE
Consider using a single version for all of the components

### ISSUE THREAD

**Issue by andreaTP** [microsoft/kiota-java#119]
Hi all, and thanks for the amazing project!

Working with Kiota I'm finding it a bit painful to mix and match the various support libraries versions (abstractions, serialization etc. etc.).
Here I'm proposing to use a single version in this repository and release everything altogether every time.
I understand that this might seem "incorrect" from the semantic point of view, but, since releases are cheap(after the initial setup) I do believe that the benefits are counterbalancing the cons.

Having a single version consistent across the artifacts makes cleaner build files for the users and reduces friction.
e.g. a Maven `pom.xml` might look like this:

```xml
...
  <properties>
    <kiota.version>0.1.0</kiota.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-abstractions</artifactId>
      <version>${kiota.version}</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-http-okHttp</artifactId>
      <version>${kiota.version}</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-serialization-json</artifactId>
      <version>${kiota.version}</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-serialization-text</artifactId>
      <version>${kiota.version}</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-serialization-form</artifactId>
      <version>${kiota.version}</version>
    </dependency>
  </dependencies>
  ...
```

**Comment by baywet** [comment]
Thank for the suggestion and the PR at #118!
Glad you like kiota, out of curiosity did you see that the info command with a language parameter gives you the list of dependencies?
What would be the equivalent "shorthand" for Gradle?

I understand that would "force" us to release all packages every-time we make a change, potentially pushing more updates on customers (thinking of dependabot here and the added noise), correct?

The versioning strategy is usually left up to the language implementer (our team is divided by language). If all of them follow semver, they do have a degree of freedom, and kiota typescript for example also versions packages together (although the tooling give you a choice not to version specific packages).

**Comment by andreaTP** [comment]
> did you see that the info command with a language parameter gives you the list of dependencies?

oh, it was not working the last time I tested it, but now it works great!

> What would be the equivalent "shorthand" for Gradle?

the standard way of providing several libraries versions in Java is using the Maven [bill of material/BOM](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms) which is also [supported by Gradle](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import)

It should be pretty doable to automate the publishing of a BOM generated from the `kiota` CLI 🙂

**Comment by andreaTP** [comment]
> I understand that would "force" us to release all packages every-time we make a change, potentially pushing more updates on customers (thinking of dependabot here and the added noise), correct?

Dependabot is pretty smart about Java dependencies here you can find an example where in a single PR it's updating 4 libraries changing a single property (i.e. a single line):
https://github.com/Apicurio/apicurio-registry/pull/3044

**Comment by andreaTP** [comment]
> The versioning strategy is usually left up to the language implementer (our team is divided by language). 

I totally agree and understand that this should ultimately be a decision of the team of maintainers, I was proposing the "single version" approach as it requires(IMHO) less maintenance burden (e.g. you don't need to execute multiple releases), but I wouldn't oppose if you prefer the BOM approach.

**Comment by baywet** [comment]
> It should be pretty doable to automate the publishing of a BOM generated from the kiota CLI

On business we're staying out of on purpose is "project configuration management". This is one of the tenants of Kiota's design principles. The reasoning being project configuration files and project structure vary a lot from eco-system to eco-system. They change overtime (rapidly in some cases), or are multiple options in some others (like Java with gradle and maven). Fiddling with that aspect would be an easy way to mess up customer's projects over time and would add a significant maintenance burden on our team. Do you think documenting the BOM would be enough for the time being? and maybe extensions like #120 can handle the BOM aspect if people desire a deep integration with their IDE? Is there an alternative that would allow people to specify a single version from the build.gradle dependencies without having to rely on a BOM?

> I totally agree and understand that this should ultimately be a decision of the team of maintainers, I was proposing the "single version" approach as it requires(IMHO) less maintenance burden (e.g. you don't need to execute multiple releases), but I wouldn't oppose if you prefer the BOM approach.

One issue this would solve is when releases are inter-dependent, usually we need to force merge and re-run the workflows, pretty messy at the time.

**Comment by andreaTP** [comment]
> Do you think documenting the BOM would be enough for the time being?

documenting it is the first step for sure, but in case you want to stick with different versions for each module, emitting a BOM is very much expected and should be easy enough to achieve (e.g. we can try something like: https://github.com/gradle-bom/gradle-bom-generator-plugin ).

> maybe extensions like https://github.com/microsoft/kiota-java/issues/120 can handle the BOM aspect if people desire a deep integration with their IDE?

that's possible, but we would need to invest in this aspect and I understand that is out of the project goals.

> Is there an alternative that would allow people to specify a single version from the build.gradle dependencies without having to rely on a BOM?

If the versions are aligned you can declare them like: https://stackoverflow.com/a/48577618 and re-use the value.
In Maven you normally bind them to `properties` as shown in the example on the top.
If versions are not aligned pretty much everyone is publishing a BOM to reduce the risk of issues on the classpath ( [e.g.](https://github.com/fabric8io/kubernetes-client/blob/980b385fd30a039f1f911db467dd3fb7a24fa3a1/doc/FAQ.md#ive-tried-adding-a-dependency-to-kubernetes-client-but-im-still-getting-weird-class-loading-issues-what-gives) ) which are extremely tedious and cumbersome to be solved ...

**Comment by andreaTP** [comment]
> I don't think that providing a bom makes a lot of sense when we consider alternative implementations. It's kind of a lock in to predefined choices. Does that make sense?

Not really, BOM works by providing the default values for unspecified versions which can always be overwritten in user's land.

> From what has been exposed here I agree that aligning versions would make life simpler not only for us but also for consumers. The only downside being additional versions when not needed which comes at a marginal cost.

I agree 🙂 

> please go ahead and align versions in the outstanding PR.

The open PR is already big enough IMHO, if you don't mind I can address this point in a follow-up PR.
