### ISSUE TITLE
Stable releases

### ISSUE THREAD

**Issue by andreaTP** [microsoft/kiota-java#122]
I understand that there are still tasks to be performed to reach GA #32 but using `SNAPSHOT` versions of artifacts is an extremely bad practice as they are mutable (it's a moving tag) and they might conflict with local development versions of the libraries.

In practice, `SNAPSHOT` versions are normally used only by developers of the libraries themselves.

I encourage you to start publishing stable releases and reference only them from [the rest of the tooling](https://github.com/microsoft/kiota/blob/22479d293e33ba4fc56c6b62cd835f617a565241/src/kiota/appsettings.json#L56).

You can consider cutting corners and publishing [using JitPack](https://docs.jitpack.io/building/) instead of Maven Central as a temporary stop-gap solution (I can help with this setup).

Publishing final versions to Maven Central requires the involvement of someone in the maintainers' team with all of the needed accesses.

**Comment by baywet** [comment]
Thanks for calling this out.
We (Microsoft) do have very strict requirements when it comes to where and how we publish packages for security reasons. After a quick search on our internal engineering portal, it doesn't look like jitpack is a vetted approach.
Our account is already setup to publish on maven central and our CI is already configured to do so.
In theory it's just a matter of swapping [this task](https://github.com/microsoft/kiota-java/blob/2960c9ee3ef104cdba0baa21d8108c18f73f3df6/.github/workflows/release-component.yml#L25) to [that task](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/4437a802edf54571dbe4aa5eadd3a1a3c65488d9/.github/workflows/build-and-publish.yml#L14).

I'd say that at this point we're long overdue to publish these libraries on maven central (with a 0 major version to signal parts are still moving) and that I'm surprised the security team hasn't come to up to tell us to publish already. So please go ahead and make that modification in #118

**Comment by andreaTP** [comment]
Looking forward for `0.1.0` to see if the badge works 😛 :
https://github.com/microsoft/kiota-java#kiota-java-libraries

**Comment by baywet** [comment]
putting the final touches as we speak, I got a failure for snapshot because the local.properties and the secring are only looked at the root of each sub project. Added a copy task to the workflow.

**Comment by baywet** [comment]
unfortunately a recent policy change is impacting our ability to release, more details on #128

**Comment by andreaTP** [comment]
@baywet thanks for looking into this and sorry for the noise I caused here, should we re-open this issue?

**Comment by baywet** [comment]
no, the breakage is not related to your changes, I was able to confirm that.
This is why I opened a separate issue to track that.
Your work is really appreciated and greatly improves the overall project structure. thanks again!
