### ISSUE TITLE
Split package issue

### ISSUE THREAD

**Issue by Sineaggi** [microsoft/kiota-java#1224]
As per The Java Module System ([link](https://livebook.manning.com/concept/java/split-package#:~:text=Packages%20should%20have%20a%20unique,compile%20or%20launch%20such%20configurations.)), classes shouldn't be in the same package across two separate jars.

Azure authentication classes and the serialization libraries already conflict, the former in package `com.microsoft.kiota.authentication` and the later in `com.microsoft.kiota.serialization`.

I'd propose moving the classes in each of those modules to the respective module names (for example, the ones listed in https://github.com/microsoft/kiota-java/issues/1108#issuecomment-1976623974).

**Comment by baywet** [comment]
Hi @Sineaggi 
Thanks for starting a discussion on this.
While I understand it shouldn't be done in theory, lots of projects do this.
For example, Open Telemetry has items in `io.opentelemetry.semconv` split across two jars `opentelemetry-semconv`, and `opentelemetry-semconv-incubating`.

Can you articulate further what issues does that cause, please?

Also if @andreaTP could join the conversation for this one, I'd appreciate it.

**Comment by andreaTP** [comment]
Thanks for getting me in the loop @baywet , honestly I'm not a java modules expert.

The best I can do is try to summon @aalmiray as he is usually of great help and knowledgeable about the subject.
🙏

**Comment by aalmiray** [comment]
This is know as "split packages" and they are indeed forbidden in the Java Module System.

A given package name can only be found inside an specific module.
Currently a JAR file contains a single module. 
Therefore there can only be a given package name in a JAR file. 

There are tools that can help you find packages split across JAR/module boundaries. I can recommend  https://github.com/kordamp/jarviz 😅😉

**Comment by baywet** [comment]
Thanks for chiming in @aalmiray !!!
@Sineaggi while I understand that modules would not load, which limits which platforms kiota java can be used with, changing this now would be a source breaking change, and mandate a major rev of the libraries here but also the generator itself.
We're unlikely to make that change soon on itself as we'll want to coordinate with other breaking changes and batch them.
