### ISSUE TITLE
Sonar check doesn't work on external forks

### ISSUE THREAD

**Issue by andreaTP** [microsoft/kiota-java#123]
I propose disabling the Sonar check on pull requests as we did e.g. here:
https://github.com/java-operator-sdk/java-operator-sdk/blob/36917750e04018dc44a823535e7273d697391bdb/.github/workflows/sonar.yml#L24

It's not ideal, but the check will continue to be performed on `main` and on branches in this repo so that you can target any issue right after a PR is merged.

**Comment by baywet** [comment]
Thanks for pointing this. I don't think we'll be able to do much about that (to actually run sonarcloud).
Secrets (the sonarcloud token) [are not accessible to PRs that originate from forks](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) and our security and compliance team has disabled the ability for us to make secrets available.
This is the main reason why we're not enforcing sonarcloud as a check at the moment.
One alternative would be to [check the presence of the secret in a first job](https://github.com/microsoft/kiota/blob/main/.github/workflows/sonarcloud.yml) and if we wanted to enforce the check, we'd need a second workflow with the same name and job name that checks the token is not present and NOOPs.
But in any case, PRs from forks won't be able to run the actual workflow.

**Comment by andreaTP** [comment]
> PRs from forks won't be able to run the actual workflow

Your analysis is sadly correct, and the reason why I proposed disabling it on forks.

**Comment by baywet** [comment]
We don't have access to these settings. Our best best is probably the check token solution I was suggesting. Do you mind making the change in your existing PR?

**Comment by andreaTP** [comment]
I proposed a possible solution that has been effective in other repos I contributed to, let me know if it works for you.
