### ISSUE TITLE
BaseRequestConfiguration#options field is set to an immutable list

### ISSUE THREAD

**Issue by m-moris** [microsoft/kiota-java#1238]
I encountered the following error while using Graph SDK for Java. Upon investigating the cause, I found that an immutable object from `Collections.emptyList()` was assigned to `com.microsoft.kiota.BaseRequestConfiguration#options`

- https://github.com/microsoftgraph/msgraph-sdk-java/issues/1933#issuecomment-2074319381

Is it possible to change this initial value to a mutable list? Is there any specific reason why an immutable list is being actively used?

https://github.com/microsoft/kiota-java/blob/5079c15eb16e2ce363585db1a19e83b6244d5ff7/components/abstractions/src/main/java/com/microsoft/kiota/BaseRequestConfiguration.java#L11-L28

**Comment by baywet** [comment]
Thanks for creating a related issue!
The fix seems pretty straight forward here, we should assign a new array list instead of using that static method.
Would you be willing to submit a pull request for it?
