### ISSUE TITLE
maven policy changes prevent pushing on snapshot and central

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-java#128]
Recent policy changes on the com.microsoft namespace are currently preventing us from publishing new versions.
We were supposed to get exceptions for com.microsoft.kiota and com.microsoft.graph but it seems they have not been filed by the security team.
This is not related to our recent workflow changes as [the following attempt](https://github.com/microsoft/kiota-java/actions/runs/3797036575/attempts/1) worked (dec 28th) but [a new attempt](https://github.com/microsoft/kiota-java/actions/runs/3797036575/attempts/2) (Jan 6th, no code changes) is failing with a 403.
I have reached out to the security team to get us unblocked and will provide updates here.

**Comment by baywet** [comment]
Update, the security team reported they didn't roll any new policy yet.
However it seems the sonatype made maintenance changes recently, opened a ticket with them https://issues.sonatype.org/browse/MVNCENTRAL-7776

**Comment by baywet** [comment]
@andreaTP Can you try to pull from maven central releases? I was apparently able to publish earlier, but I'm still not able to pull. Thanks for the help!

**Comment by baywet** [comment]
Actually nevermind, it works now for central releases which should unblock you. (it was an indexing delay). We're still unable to publish on snapshots though, still working with the maven team

**Comment by baywet** [comment]
They just fixed it! Now available also on snapshots https://github.com/microsoft/kiota-java/actions/runs/3903251941/jobs/6669045662

And to answer your question: It allows us to share changes with the broader community without risking existing projects to pull updates that might be detrimental.

Closing.

**Comment by andreaTP** [comment]
Nice job @baywet ! Happy to see a stable and published version of this project!

**Comment by baywet** [comment]
Thanks a lot for your help getting there!
