### ISSUE TITLE
How to avoid Application Insights to be spamed

### ISSUE THREAD

**Issue by dwlabcube** [microsoft/kiota-java#1446]
My App-Insights get filled very soon. Each Request logs about 10 InProcs.
How can i disable this?

![image](https://github.com/user-attachments/assets/a2d2e90b-9275-4d23-8dce-8b0de76af0b7)

Actually i am using the Java-Agent not an exporter.
Some things there can be set via Env-Vars, but unluckily the .._AZURE_SDK_ENABLED being set to false did not solve the issue.

![image](https://github.com/user-attachments/assets/6db6d3c8-431b-4d08-9dca-1c8b9440176f)

i thought there might be another env-var to be set.

the spans get set up in kiota here:
https://github.com/microsoft/kiota-java/blob/6f9a3219a543fe30525931339e33bd8ad27ae2f3/components/http/okHttp/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java#L773

**Comment by baywet** [comment]
For context this originally was posted here and workarounds were suggested.
https://github.com/microsoftgraph/msgraph-sdk-java/issues/2084

@dwlabcube thank for re-opening here. Have you explored the custom exporter option I suggested?

**Comment by dwlabcube** [comment]
Since I did not find a "Out-of-the-Box" solution for Java i thought i'd rather ask the guys who programmed it. maybe there is already an easy solution that we are just not aware of...

**Comment by baywet** [comment]
Not today. Those environment variables are used by the agent itself. So the agent would need to define and implement a new one for kiota clients. (might be worth asking them)
However it seems that [the agent offers a configurable processor](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#telemetry-processors-preview) which might allow you to mask/exclude the kiota related spans.
