### ISSUE TITLE
Kiota-Serialization-Multipart:1.8.0 missing from Maven Repository

### ISSUE THREAD

**Issue by etcoyvindf** [microsoft/kiota-java#1681]
When attempting to update our Kiota Dependencies to 1.8.0, gradle fails to find and download Kiota-Serialization-Multipart.

Browsing the web pages on November 18th 2024 shows the latest version being 1.7.0 for this package, the same with Kiota-Bundle. The others are available in version 1.8.0. Link to mvn: https://mvnrepository.com/artifact/com.microsoft.kiota/microsoft-kiota-serialization-multipart

Ouytput from Gradle:
```
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.microsoft.kiota:microsoft-kiota-serialization-multipart:1.8.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/microsoft/kiota/microsoft-kiota-serialization-multipart/1.8.0/microsoft-kiota-serialization-multipart-1.8.0.pom
       - https://mvnrepository.com/com/microsoft/kiota/microsoft-kiota-serialization-multipart/1.8.0/microsoft-kiota-serialization-multipart-1.8.0.pom
       - https://repo.maven.apache.org/maven2/com/microsoft/kiota/microsoft-kiota-serialization-multipart/1.8.0/microsoft-kiota-serialization-multipart-1.8.0.pom
     Required by:
         root project :
```

I'm unsure if maven central still needs time to find these, or if there was some error in deployment.

**Comment by baywet** [comment]
Hi @etcoyvindf 
Thank you for using kiota and for reaching out.

Indeed, the CD [failed](https://github.com/microsoft/kiota-java/actions/runs/11834184555), I just requeued the failed jobs. Let's see what happens in the next 30 minutes or so.

**Comment by baywet** [comment]
The release was successful! Closing.
Let us know if you have any additional comments or questions.
