### ISSUE TITLE
0.3.2 not(yet?) available on Maven Central

### ISSUE THREAD

**Issue by andreaTP** [microsoft/kiota-java#244]
Publishing version 0.3.2 has been successful but the artifacts are not available yet on Maven Central.
Hopefully, this is just a sync delay ... but let's keep an eye on it.

**Comment by baywet** [comment]
Thanks for bringing this up. Somehow the bump of the version in gradle.properties was missed. this should be solved with #245

**Comment by andreaTP** [comment]
Thanks for looking into this as always @baywet !
I confirm this is now fixed!
