### ISSUE TITLE
unit tests for the libraries - java

### ISSUE THREAD

**Issue by ddyett** [microsoft/kiota-java#31]
Tracks to work to implement unit testing for Kiota libraries.

- [x] Abstractions
- [x] Middleware
- [ ] Serialization
- [ ] ClientFactory
- [ ] RequestAdapter
- [ ] Callback Wrapper
- [x] https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/239

**Comment by petrhollayms** [comment]
Team agreement on having sufficient code coverage for now and adding new unit tests for all new features and bug fixes in alignment with our new Definition of Done, so closing for now.
