### ISSUE TITLE
Remove usage of reflection from `abstractions`

### ISSUE THREAD

**Issue by andreaTP** [microsoft/kiota-java#923]
The libraries are currently using reflection in 4 different places (if I'm not missing something):

- `ApiClientBuilder` - `abstractions`
- `RequestInformation` - `abstractions`
- `KiotaSerialization` - `abstractions`
- `JsonSerializationWriter` - `serialization/json`

As ppl can roll their json serialization support I'm not concerned with the latter.
But, the usage of reflection in `abstractions` means that this is not going to run without configuration when compiled with [`native-image`](https://www.graalvm.org/22.0/reference-manual/native-image/), especially for the usage in Quarkus applications.

Since we are in control of the generator, I do believe that we can find solutions to completely avoid the usage of reflection in the `abstractions` layer.

**Comment by baywet** [comment]
Thanks for starting this.
Yes this should be easy to remove from the builder, and you started the work.
For request information, this should only be present for the query parameters, and maybe for the request options, and I'm not sure there is a way around that?
For serialization, the methods have overloads where you can pass the factory method to avoid using reflection already, so we should be good here.

**Comment by andreaTP** [comment]
> For request information, this should only be present for the query parameters, and maybe for the request options, and I'm not sure there is a way around that?

We should be able to generate(as source) a static method to retrieve the field list and the needed information with a plain method call. Would you consider such an approach?

> For serialization, the methods have overloads where you can pass the factory method to avoid using reflection already, so we should be good here.

Agreed, I'll review this detail before closing the issue.

**Comment by baywet** [comment]
> We should be able to generate(as source) a static method to retrieve the field list and the needed information with a plain method call. Would you consider such an approach?

I'd like to explore that in more details:
If the method just returned a list of field names, we'd still need reflection to get the values + serialization name.
If the method returned directly the query parameters key + value, it'd still need reflection to get to the attribute in case the query parameter serialization name is different from the symbol name.
I don't see benefits from pushing that to the code gen, and it comes at a size price.
In dotnet, native compilation relies on attributes that basically mean "yes you can trim things, except for the argument to this method, because the method will list out the fields of the passed type" giving us the best of both worlds. Is there something similar to that in Java native?

**Comment by andreaTP** [comment]
> Is there something similar to that in Java native?

Kind of, but pretty tricky to setup: https://www.graalvm.org/jdk17/reference-manual/native-image/dynamic-features/Reflection/#manual-configuration and this will need to be done for the generated code ...

> If the method just returned a list of field names, we'd still need reflection to get the values + serialization name.
If the method returned directly the query parameters key + value, it'd still need reflection to get to the attribute in case the query parameter serialization name is different from the symbol name.

I'm not sure I follow here, I might be missing some invariants, but returning a `Map<String, Value>` with the serialization names as keys and the value (or a "getter" method for it) should cover the use-case, am I missing something?

> I don't see benefits from pushing that to the code gen

I really think that we should avoid as much as possible any kind of usage of reflection, it's slow, hard to debug and difficult to handle on some(widespread) runtimes like GraalVM.
I'm open to hear alternative approaches thought!

> it comes at a size price

This is possible, but I do see similarities with the ser/deser generated methods, maybe we will be able to "refactor" the generated code to reduce the LoC size (but haven't attempted).

**Comment by andreaTP** [comment]
Correct, but I'd envision the possibility to refactor the code with the generated `getFieldDeserializers` method as the logic is gonna be pretty similar.

**Comment by ramsessanchez** [comment]
Hi @andreaTP , I'll kick off a generation with the updated Kiota-Java versions. A new preview release should be available later today or EOD.

**Comment by ramsessanchez** [comment]
6.0.2-SNAPSHOT is now available for v1 , beta shortly

**Comment by andreaTP** [comment]
thanks, @ramsessanchez 👍 I'll try to test everything tomorrow!

**Comment by andreaTP** [comment]
> 6.0.2-SNAPSHOT is now available for v1 , beta shortly

Trying to connect the dots, are you sure that this version number is correct?

**Comment by baywet** [comment]
that's for Microsoft Graph, are you testing Microsoft Graph as well?

**Comment by andreaTP** [comment]
No 😅

**Comment by baywet** [comment]
with #957 we've just achieved a reflection free kiota java, thanks everyone for the help and the great work! closing.

**Comment by andreaTP** [comment]
Thanks for the support in this quest!
